/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wineshoppalette;

import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Alessandro
 */
public class Interface extends javax.swing.JFrame {
    private static Vector<Vino> prodotti;
    private ImageIcon grechetto = new ImageIcon("grechetto.png");
    private JLabel imageLabel = new JLabel(grechetto);
    
    private ImageIcon montefalco = new ImageIcon("montefalco.png");
    private JLabel imageLabelMnt = new JLabel(montefalco);
    
    public Interface(Vector<Vino> prodotti) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelType = new javax.swing.JLabel();
        labelWineList = new javax.swing.JLabel();
        labelQuantity = new javax.swing.JLabel();
        labelPiecesAvailable = new javax.swing.JLabel();
        labelPrice = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        buttonAddCart = new javax.swing.JButton();
        buttonConfirm = new javax.swing.JButton();
        buttonReset = new javax.swing.JButton();
        typeComboBox = new javax.swing.JComboBox();
        wineListComboBox = new javax.swing.JComboBox();
        comboBoxQuantity = new javax.swing.JComboBox();
        piecesAvailable = new javax.swing.JLabel();
        panelImage = new javax.swing.JPanel();
        labelGrechetto = new javax.swing.JLabel();
        labelMontefalco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelType.setText("Selezionare Bianco o Rosso");

        labelWineList.setText("Lista Vini");

        labelQuantity.setText("Quantità");

        labelPiecesAvailable.setText("Pezzi Disponibili");

        labelPrice.setText("Prezzo Cadauno");

        labelTotal.setForeground(new java.awt.Color(255, 0, 0));
        labelTotal.setText("Costo Totale");

        price.setText("jLabel7");

        total.setText("jLabel8");

        buttonAddCart.setText("Aggiungi al carrello");

        buttonConfirm.setText("Conferma Ordine");

        buttonReset.setText("Reset");

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rosso", "Bianco", " " }));
        typeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeComboBoxActionPerformed(evt);
            }
        });

        wineListComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wineListComboBoxActionPerformed(evt);
            }
        });

        piecesAvailable.setText("jLabel7");

        labelGrechetto.setText("jLabel7");

        labelMontefalco.setText("jLabel7");

        javax.swing.GroupLayout panelImageLayout = new javax.swing.GroupLayout(panelImage);
        panelImage.setLayout(panelImageLayout);
        panelImageLayout.setHorizontalGroup(
            panelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImageLayout.createSequentialGroup()
                        .addComponent(labelGrechetto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(56, 56, 56))
                    .addGroup(panelImageLayout.createSequentialGroup()
                        .addComponent(labelMontefalco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        panelImageLayout.setVerticalGroup(
            panelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImageLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(labelMontefalco)
                .addGap(26, 26, 26)
                .addComponent(labelGrechetto)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPrice)
                            .addComponent(labelQuantity)
                            .addComponent(labelTotal)
                            .addComponent(labelPiecesAvailable)
                            .addComponent(labelType, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelWineList, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(wineListComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(typeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboBoxQuantity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(piecesAvailable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(price, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(buttonReset, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonAddCart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonConfirm)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(panelImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(621, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelType)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wineListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelWineList))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBoxQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(labelPiecesAvailable))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(piecesAvailable)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(price)
                            .addComponent(labelPrice))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTotal)
                            .addComponent(total))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonAddCart)
                            .addComponent(buttonConfirm)))
                    .addComponent(panelImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonReset)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboBoxActionPerformed
        // TODO add your handling code here:
         wineListComboBox.removeAllItems();
            if(typeComboBox.getSelectedItem().equals("Bianco")){
                for(int i=0; i < this.prodotti.size(); i++){
                       if(this.prodotti.elementAt(i).isBianco())
                           wineListComboBox.addItem(this.prodotti.elementAt(i).getNome());
                    }
            }
            else{
                if(typeComboBox.getSelectedItem().equals("Rosso")){
                    wineListComboBox.removeAllItems();
                    comboBoxQuantity.removeAllItems();
                    for(int i=0; i< this.prodotti.size(); i++){
                        if(this.prodotti.elementAt(i).isRosso()){
                            wineListComboBox.addItem(this.prodotti.elementAt(i).getNome());
                        }
                    }
                }
            }
    }//GEN-LAST:event_typeComboBoxActionPerformed

    private void wineListComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wineListComboBoxActionPerformed
        // TODO add your handling code here:
        comboBoxQuantity.removeAllItems();
            for(int i=0; i < this.prodotti.size(); i++){
                if(this.prodotti.elementAt(i).getNome().equals(wineListComboBox.getSelectedItem()))
                    for(int j=0; j <= this.prodotti.elementAt(i).getPezziDisponibili(); j++){
                        comboBoxQuantity.addItem(j);
                        piecesAvailable.setText(""+this.prodotti.elementAt(i).getPezziDisponibili());
                        if(prodotti.elementAt(i).getNome().equals("Montefalco")){
                            labelMontefalco.setVisible(false);
                            imageLabelMnt.setVisible(true);
                        }
                        else{
                            if(prodotti.elementAt(i).getNome().equals("Grechetto")){
                                imageLabelMnt.setVisible(false);
                                imageLabel.setVisible(true);
                            }
                        }
                       
                    }
                }
    }//GEN-LAST:event_wineListComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Vino vino = new Vino("Montefalco", 25, 20, false, true);
        Vino vino1 = new Vino("Grechetto", 5, 25, true, false);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface(prodotti).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddCart;
    private javax.swing.JButton buttonConfirm;
    private javax.swing.JButton buttonReset;
    private javax.swing.JComboBox comboBoxQuantity;
    private javax.swing.JLabel labelGrechetto;
    private javax.swing.JLabel labelMontefalco;
    private javax.swing.JLabel labelPiecesAvailable;
    private javax.swing.JLabel labelPrice;
    private javax.swing.JLabel labelQuantity;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelType;
    private javax.swing.JLabel labelWineList;
    private javax.swing.JPanel panelImage;
    private javax.swing.JLabel piecesAvailable;
    private javax.swing.JLabel price;
    private javax.swing.JLabel total;
    private javax.swing.JComboBox typeComboBox;
    private javax.swing.JComboBox wineListComboBox;
    // End of variables declaration//GEN-END:variables
}
